version: '3.4'

services:
  birthdaybotserver:
    image: server
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      TZ: "America/Los_Angeles"
    ports:
      - 50055:50055
    volumes:
      - data:/app/data

  birthdaybotclient:
    image: client
    build:
      context: client
      dockerfile: ./Dockerfile
    environment:
      TZ: "America/Los_Angeles"
    ports:
      - 5173:5173
    volumes:
      - data:/app/data
  
  birthdaybotcommserver:
    image: commserver
    build:
      context: commserver
      dockerfile: ./Dockerfile
    environment:
      TZ: "America/Los_Angeles"

volumes:
  data:
